---
title: "Gapminder dataset analysis"
author: "Dr Paul Williamson"
date: "03/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Open Libraries

```{r}
library(tidyverse)
library(plotly)
library(hrbrthemes)
library(viridis)
library(gridExtra)
library(gapminder)
```


## Wrangle data

Keep only data for 2007, then drop year column

```{r}
data <- gapminder %>% filter(year=="2007") %>% select(-year)
```

Add a new column ('text') which contains plot data labels for each country

```{r}
data <- data %>% 
  mutate(gdpPercap=round(gdpPercap,0)) %>% 
  mutate(pop=round(pop/1000000,2)) %>%
  mutate(lifeExp=round(lifeExp,1)) %>%
  arrange(desc(pop)) %>%
  mutate(country = factor(country, country)) %>%
  mutate(text = paste("Country: ", country,
                      "\nPopulation (M): ", pop,
                      "\nLife Expectancy: ", lifeExp, 
                      "\nGDP per Capita: ", gdpPercap,
                      sep=""))
```

## Build chart

```{r}
ggplot(data=data, 
       aes(x=gdpPercap, y=lifeExp, size=pop, color=continent, text=text)) +
  geom_point(alpha=0.7)
```


```{r}
p <- ggplot(data=data, 
       aes(x=gdpPercap, y=lifeExp, size=pop, color=continent, text=text)) +
  geom_point(alpha=0.7) +
  scale_size(range = c(1.4, 19), name="Population (M)") +
  scale_color_viridis(discrete = TRUE, guide=FALSE) +
  theme_ipsum() +
  theme(legend.position="none")

ggplotly(p, tooltip="text")
```